### ISSUE TITLE
message of NaN on normals on valid geometry

### ISSUE THREAD

**Issue by aron-aerosim** [AeroSim-CFD/lnas#9]
When trying to run a simulation with a STL with bad quality the simulation accuses that there are triangles with  NaN in normals. The STL does not contain faces with area 0 or triangles with very bad quality. At least the geometry is good enough for stl2lnas to be able to transform it without issues.

Possible solution: use double instead of float for geometrical operations.

geometry:  
[Aero_Sim_HDB_v1.stl.zip](https://github.com/user-attachments/files/18127937/Aero_Sim_HDB_v1.stl.zip)

transformations to apply:
```yaml
          - transformation:
                translation: [-3569.5809326171875, -306.52301025390625, 0.0]
                fixed_point: [0,0,0]
                rotation: [0,0,0]
                scale: [1,1,1]
            bodies_apply: [Aero_Sim_HDB_v1.stl]
            probes_apply: []
            point_clouds_apply: []
          - transformation:
                translation: [0, 0, 0]
                fixed_point: [0,0,0]
                rotation: [0,0,1.3264502315156903]
                scale: [1,1,1]
            bodies_apply: [Aero_Sim_HDB_v1.stl]
            probes_apply: []
            point_clouds_apply: []
          - transformation:
                translation: [0, 0, 0]
                fixed_point: [0,0,0]
                rotation: [0,0,0]
                scale: [0.0625,0.0625,0.0625]
            bodies_apply: [Aero_Sim_HDB_v1.stl]
            probes_apply: []
            point_clouds_apply: []
```
